### part one

In [2]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

If i want to transform this list into an array

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
type(mylist)

list

In [6]:
arr = np.array(mylist)

In [7]:
type(arr)

numpy.ndarray

#### matrix

In [12]:
my_list_2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
my_list_2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(my_list_2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
my_matrix = np.array(my_list_2)

#### size of the my matrix as an array

In [17]:
my_matrix.shape

(3, 3)

In [20]:
my_matrix_3 = np.array(my_list_2)

my_matrix_3.shape

(3, 3)

#### arange method

In [21]:
np.arange(0, 10) # 0 is inclusive and 10 is exclusive

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [23]:
np.arange(0, 25, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

#### zeros and ones

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
type(0.0)

float

In [27]:
type(0.)

float

In [28]:
np.zeros((5, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### nice operations for every single cell of the numpy array

In [29]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
np.ones((3,3)) + 5

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [32]:
np.ones((5, 5)) * 100

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

In [34]:
np.ones((5, 5)) / 10

array([[0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1]])

In [35]:
[1, 2, 3, 4] * 100

[1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,


#### linspace

In [36]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [37]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [38]:
len(np.linspace(0, 10, 20))

20

#### identity matrix

In [40]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
np.eye(5, 6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

### part two

In [45]:
np.random.rand(4)

array([0.56483603, 0.40191514, 0.66808042, 0.83378906])

In [46]:
np.random.rand(5, 5)

array([[0.46272187, 0.94596881, 0.66964008, 0.71117409, 0.01769012],
       [0.89061123, 0.49838473, 0.71234171, 0.95765359, 0.31381559],
       [0.10901786, 0.46507551, 0.30098743, 0.44638808, 0.27672249],
       [0.9507129 , 0.38941646, 0.65126481, 0.4167317 , 0.13282471],
       [0.41988134, 0.8219817 , 0.97486165, 0.26478052, 0.7506727 ]])

In [48]:
np.random.randn(10)

array([-0.00983592, -0.19142325, -1.40652614,  0.28909963, -0.18659122,
       -2.58611075,  1.17581867, -0.77023972, -0.96695873,  0.65542444])

In [49]:
np.random.randint(1, 100, 10)

array([24, 94, 21, 95, 22,  8, 22, 78,  7, 52])

#### random state to get same results

In [51]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [52]:
np.random.rand(4)

array([0.68527698, 0.83389686, 0.30696622, 0.89361308])

In [53]:
np.random.rand(4)

array([0.72154386, 0.18993895, 0.55422759, 0.35213195])

#### shape converting

In [54]:
arr_1 = np.arange(25)

In [55]:
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [58]:
arr_1.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
arr_1.reshape(5, 3) # array size does not conform to (5,3)

ValueError: cannot reshape array of size 25 into shape (5,3)

In [69]:
rand_arr = np.random.randint(0, 50, 10)

In [70]:
rand_arr

array([19, 35, 28,  7, 10, 39, 38, 46,  9, 18])

In [71]:
rand_arr.max()

46

In [72]:
rand_arr.min()

7

In [73]:
rand_arr.mean()

24.9

#### what are the index locations of the max and min values?

In [74]:
rand_arr.argmax() # returns index

7

In [75]:
rand_arr.argmin() # returns index

3

#### data type

In [76]:
rand_arr.dtype

dtype('int64')

### Indexing and Selection

In [3]:
new_arr = np.arange(0, 11)

In [5]:
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
new_arr[9]

9

In [7]:
new_arr[1:5]

array([1, 2, 3, 4])

In [8]:
new_arr[:3]

array([0, 1, 2])

In [9]:
new_arr[-2:]

array([ 9, 10])

In [10]:
new_arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [11]:
new_arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [12]:
new_arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [13]:
slice_of_array = new_arr[0:6]

In [14]:
slice_of_array

array([0, 1, 2, 3, 4, 5])

In [15]:
slice_of_array[:] = 99

#### copy array

In [16]:
arr_copy = new_arr.copy()

In [18]:
id(arr_copy), id(new_arr)

(137286346916944, 137286616571024)

In [19]:
id(arr_copy) == id(new_arr)

False

In [20]:
arr_copy[:] = 1000

In [21]:
arr_copy

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [22]:
new_arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

#### Indexing on 2d array

In [24]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [25]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
arr_2d.shape

(3, 3)

In [28]:
arr_2d[1] # returns row

array([20, 25, 30])

In [29]:
arr_2d[1][2]

30

In [30]:
arr_2d[1,2]

30

In [31]:
arr_2d[2,2]

45

In [36]:
arr_2d[0:2,1:3]

array([[10, 15],
       [25, 30]])

#### conditional selection

In [38]:
con_arr = np.arange(1, 11)

In [39]:
con_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
con_arr > 7

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [42]:
con_arr[con_arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [43]:
bool_arr = con_arr > 4

In [44]:
con_arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])